### ISSUE TITLE
Problems for installation - Could you help me ?

### ISSUE THREAD

**Issue by Dragomitch** [jy95/P4ng#2]
C:\Users\jesui\P4ng>npm run  packagerApp

> p4ng@1.0.0 packagerApp C:\Users\jesui\P4ng
> scripts/packager-script.sh

'scripts' n’est pas reconnu en tant que commande interne
ou externe, un programme exécutable ou un fichier de commandes.

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Users\\jesui\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "packagerApp"
npm ERR! node v7.0.0
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! p4ng@1.0.0 packagerApp: `scripts/packager-script.sh`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the p4ng@1.0.0 packagerApp script 'scripts/packager-script.sh'.
npm ERR! Make sure you have the latest version of node.js and npm [installed.]

[https://puu.sh/sPESS/537006d838.png](url)

**Comment by jy95** [comment]
Bash scripts are working only on Linux, sir. Maybe time to use some true operating system ?

**Comment by jy95** [comment]
If the script still doesn't work on Linux , do what the script should do manually.

**Comment by Dragomitch** [comment]
Well, why do you do something multiplatform (because that's the scope of using electron and nodejs) if it isn't :/

**Comment by jy95** [comment]
Because the original programmer (not me) wrote his script in Bash Script and he didn't know about multiplatform Unix commands module like https://www.npmjs.com/package/shelljs

**Comment by jy95** [comment]
Fixed in this commit : https://github.com/jy95/P4ng/commit/06932608ca8fd32f900bc8829f25f7a1dc76ee2f
